USE DOSIRAK;
DROP TABLE IF EXISTS ANSWER CASCADE;

CREATE TABLE IF NOT EXISTS ANSWER (
ANSWER_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '답변코드',
ANSWER_STATUS BOOLEAN NOT NULL COMMENT '답변상태',
ANSWER_CONTENT TEXT(500) NOT NULL COMMENT '답변내용',
ANSWER_DATE DATE NOT NULL COMMENT '답변날짜',
ADMIN_ID VARCHAR(20) COMMENT '관리자아이디',
REVIEW_CODE INT(20) COMMENT '리뷰코드',
ASK_CODE INT COMMENT '문의코드',
foreign key (ADMIN_ID) references ADMIN (ID),
foreign key (ASK_CODE) references ASK (ASK_CODE)
) ENGINE=INNODB COMMENT '답변';

