USE DOSIRAK;
DROP TABLE IF EXISTS VERIFY CASCADE;

CREATE TABLE VERIFY (
    VERIFYPAGE VARCHAR(255) NOT NULL,
    VERIFYCODE VARCHAR(255) NOT NULL,
    VERIFYTIME DATETIME NOT NULL
);

select * from VERIFY;